[project]
name = "bossjob"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiomysql>=0.2.0",
    "beautifulsoup4>=4.13.4",
    "dotenv>=0.9.9",
    "mysql-connector-python>=9.3.0",
    "playwright>=1.52.0",
]
