name: boss

on:
  workflow_dispatch:
  schedule:
   - cron: "0 */4 * * *"  # 每4小时运行一次
#  push:
#    branches:
#      - main

jobs:
  boss:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        operating-system: ['ubuntu-24.04']

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # 设置你希望使用的 Python 版本

      # 缓存 pip 依赖，避免重复安装
      - name: 缓存 pip 依赖
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip  # pip 默认缓存路径
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 缓存 Playwright 浏览器依赖
      - name: 缓存 Playwright 浏览器
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright  # Playwright 浏览器缓存路径
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: 运行脚本
        run: |
          python main.py
        env:
          DB_HOST: ${{secrets.DB_HOST}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{secrets.DB_NAME}}